export default {
    CHANGE: "CHANGE",
    TOGGLE_SIDEBAR: "TOGGLE_SIDEBAR",
    ADD_RESOURCE: "ADD_RESOURCE",
    LOAD_PROJECT_DIRECTORY: "LOAD_PROJECT_DIRECTORY",
    LOAD_DIRECTORY_RESPONSE: "LOAD_DIRECTORY_RESPONSE",
};